Repository team-christmas/todowith-fe, pull requests merged in 2021-12, with the labels that each got.

#5 feat : 불필요한 파일 삭제 및 eslint이슈 일부 수정
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement

#4 fix: Eslint 디펜던시 에러 해결
  .eslintrc.js
  package-lock.json
  package.json
  yarn.lock
Labels: bug

#6 style: airbnb-eslint에 맞게 기본스타일 변경
  .eslintrc.js
  src/App.jsx
  src/index.jsx
Labels: enhancement

#7 refactor: 깃 이그노어 수정
  .gitignore
Labels: enhancement

#8 feat: eslint 와 prettier 설정
  .eslintrc.js
  .prettierrc.js
  jsconfig.json
  src/App.jsx
  src/index.jsx
Labels: documentation
